### ISSUE TITLE
Website generation of the project Credit Risk Analysis

### ISSUE THREAD

**Issue by eeshan15** [The-Red-Wood-Lab/Credit-Risk-Analysis#13]
Generate a website for the credit risk analysis project which tells about the project briefly.

**Comment by swarupsahu08** [comment]
hey @eeshan15 Assign me this issue

**Comment by eeshan15** [comment]
@swarupsahu08 Issue assigned please work accordingly as mentioned earlier. Thank you.

**Comment by swarupsahu08** [comment]
yah ok I am trying my best to contribute

**Comment by eeshan15** [comment]
@swarupsahu08 also don't forget to add the same labels as issue has into your PR in order to get merged.

**Comment by swarupsahu08** [comment]
@eeshan15 ,Can you see the pull request approve it or you can tell if you want any variations

**Comment by swarupsahu08** [comment]
> @swarupsahu08 also don't forget to add the same labels as issue has into your PR in order to get merged.

you are going to add the labels while merging

**Comment by swarupsahu08** [comment]
@eeshan15 is it ok you can check the link there
